import { Column, Entity, PrimaryColumn } from 'typeorm';
import type { UnitType } from '@p2h/shared';

/** A physical piece of equipment that can be inspected (table: units). */
@Entity({ name: 'units' })
export class UnitEntity {
  /** Client/seed-provided UUID; never generated by the database. */
  @PrimaryColumn('text')
  id!: string;

  @Column('text')
  code!: string;

  @Column('text')
  name!: string;

  @Column('text')
  type!: UnitType;

  @Column('text')
  site!: string;
}
